### ISSUE TITLE
if Winner window loses focus, next CHOOSE fails

### ISSUE THREAD

**Issue by DigitalDavo** [Gear61/Random-Name-Picker#27]
If you tap outside of the "And the lucky winner is ...." popup window and then hit CHOOSE nothing happens - you get no new choice.

If you select any of the 3 say name, copy text or ok options from this popup your next choice works, but not if you tap outside the white area of this popup.

You need to go out of the list to the main main, back to the list to get the CHOOSE function to work again, so there is a workaround, but seems like an unfortunate bug.

**Comment by Gear61** [comment]
The dialog needs to be dismissed in order for the rest of the UI to be clickable. To the best of my knowledge, that's how all dialogs in Android work. If you think this functionality isn't good, you can file an issue on the library I use to show dialogs in this app: [Material Dialogs](https://github.com/afollestad/material-dialogs)

**Comment by DigitalDavo** [comment]
If I download the sample Material Dialogs app, and take the first example - BASIC (NO TITLE). Once the dialogue draws, tap anywhere outside the window it closes. Now tap BASIC (NO TITLE) again and you get the dialogue again as expected.

But, 
If I hit CHOOSE in then tap outside the dialogue, and hit CHOOSE again nothing happens.

Lovely little app but this seems like an obviously broken bit.

**Comment by Gear61** [comment]
Oh wait, my apologies, I misinterpreted your bug report. My phone has an old build where you can't tap outside the modal to dismiss it, which is why I thought your issue is that you can't tap "Choose" while the modal is up. After playing around with my emulator running a fresh development build, I see what you mean; the "Choose" button becomes a dud if you dismiss the dialog by tapping outside. I introduced a janky boolean lock to prevent stacked choice dialogs from shake detection, because I can't detect when a dialog is dismissed via clicking outside and it's now breaking this flow. I'll fix this right now with some refactoring. Thanks for your bug report!

**Comment by Gear61** [comment]
Just realized that I introduced this bug because the dialog initially wasn't cancelable (cancelable means that the dialog can be dismissed via outside tapping), and I recently deleted that line, wondering why my past self would constrain the user like that. Now I know. 😆

**Comment by Gear61** [comment]
Should be fixed with: https://github.com/Gear61/Random-Name-Picker/commit/3fab9c6611c5a1ce8cea1261f0a70dd62320a817

Let me know if you have any issues after updating your app.
