### ISSUE TITLE
use start for the left and end for the right for supporting different directions languages.

### ISSUE THREAD

**Issue by alaaalzibda** [Gear61/Random-Name-Picker#63]
https://github.com/Gear61/Random-Name-Picker/blob/5c8f6c615eec14819d9bb6a4213069f245b0d386/app/src/main/res/layout/names_list_item.xml#L12

**Comment by Gear61** [comment]
At Instagram, we believe in doing the simple thing first, and that's something I carry over into my personal projects. The reason I didn't use start/end is because this app supports a relatively low API level that doesn't have start/end, so I didn't want to have both left/right and start/end attributes on all my views. I don't think we should start using these attributes until the app starts officially supporting an RTL language.
